package org.leolo.web.nrinfo.model.networkrail.schedule;

import lombok.Getter;
import lombok.Setter;

import java.util.ArrayList;
import java.util.Date;
import java.util.Objects;
import java.util.UUID;

@Setter
@Getter
public class Schedule {
    /** This UUID is generated by me to help identify record in database */
    private UUID recordUUID;

    private String trainUID;
    private Date startDate;
    private Date endDate;
    private String daysRuns;
    private ScheduleIndicator stpIndicator;
    private String atocCode;

    /** Indicate is the train runs on bank holidays. This is for displays only. */
    private String runsOnBankHolidays;
    private String trainStatus;
    /** known as applicable_timetable in JSON */
    private boolean subjectToPerformanceMonitor;
    private String trainCategory;
    private String signallingHeadCode;
    private String reservationSystemHeadCode;
    private String trainServiceCode;
    /** Known as business_sector in JSON. This field had been repurposed */
    private String portionId;
    private String powerType;
    private String timingLoad;
    private int plannedSpeed;
    private String operatingCharacteristics;
    private boolean hasFirstClass;
    private String sleeper;
    private String reservations;
    private String catering;

    private ArrayList<ScheduleEntry> scheduleLocations = new ArrayList<>();

    @Override
    public boolean equals(Object o) {
        if (!(o instanceof Schedule schedule)) return false;
        return subjectToPerformanceMonitor == schedule.subjectToPerformanceMonitor && plannedSpeed == schedule.plannedSpeed && hasFirstClass == schedule.hasFirstClass && Objects.equals(recordUUID, schedule.recordUUID) && Objects.equals(trainUID, schedule.trainUID) && Objects.equals(startDate, schedule.startDate) && Objects.equals(endDate, schedule.endDate) && Objects.equals(daysRuns, schedule.daysRuns) && Objects.equals(runsOnBankHolidays, schedule.runsOnBankHolidays) && Objects.equals(trainStatus, schedule.trainStatus) && stpIndicator == schedule.stpIndicator && Objects.equals(atocCode, schedule.atocCode) && Objects.equals(trainCategory, schedule.trainCategory) && Objects.equals(signallingHeadCode, schedule.signallingHeadCode) && Objects.equals(reservationSystemHeadCode, schedule.reservationSystemHeadCode) && Objects.equals(trainServiceCode, schedule.trainServiceCode) && Objects.equals(portionId, schedule.portionId) && Objects.equals(powerType, schedule.powerType) && Objects.equals(timingLoad, schedule.timingLoad) && Objects.equals(operatingCharacteristics, schedule.operatingCharacteristics) && Objects.equals(sleeper, schedule.sleeper) && Objects.equals(reservations, schedule.reservations) && Objects.equals(catering, schedule.catering) && Objects.equals(scheduleLocations, schedule.scheduleLocations);
    }

    @Override
    public int hashCode() {
        return Objects.hash(recordUUID, trainUID, startDate, endDate, daysRuns, runsOnBankHolidays, trainStatus, stpIndicator, atocCode, subjectToPerformanceMonitor, trainCategory, signallingHeadCode, reservationSystemHeadCode, trainServiceCode, portionId, powerType, timingLoad, plannedSpeed, operatingCharacteristics, hasFirstClass, sleeper, reservations, catering, scheduleLocations);
    }
}
